# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7349b8c45d291d406764499ee390756157b925d2b2730db1bc8c3a386c0ab0066fe7e8af0836751c489269a8479934eb0ac950201f3fbb3579f7483fee7c2a94

test:
  secret_key_base: 5567184555fdae889bd63868ace8964524ad5a6957c9db233f177f6a8dec5df8e4a21f7c22821de3e6b5dbbe92a72ebd9e1fbd0732ef077da84990f4a6fa7f03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
